# Generated by Django 3.2.9 on 2021-11-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='back_end.course'),
            preserve_default=False,
        ),
    ]
