# Generated by Django 3.2.9 on 2021-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_tutorial_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(upload_to='', verbose_name='video/'),
        ),
    ]
